version: "3.7"

services:
    backend:
        build: ../
        expose:
            - 3200
        restart: unless-stopped
        networks:
          - web
        labels:
            - "traefik.enable=true"
            - "traefik.network=web"
            - "traefik.http.routers.api.rule=Host(`api.vaccini.vivedo.me`) && PathPrefix(`/v1`)"
        volumes:
            - ../:/app/
        command: > # installing dependencies one folder up to keep them in the container and out of the host volume
            sh -c "cd .. && cp app/package.json . && cp app/package-lock.json . &&
                 npm i && cd app/ &&
                 nodemon index.js"

networks:
    web:
        external: true