version: "3.7"

services:
  backend:
    ports:
      - 3200:3200
    command: >
      sh -c "cd .. && cp app/package.json . && cp app/package-lock.json . &&
             npm i && cd app/ &&
             nodemon index.js"